name: CI/CD Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Можно добавить pytest, если есть тесты
          # pytest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            echo "🚀 Starting deployment..."
            
            cd /home/pyScriptUploadExcelFile
            
            # Обновляем код
            git pull origin master
            
            # Обновляем зависимости
            source venv/bin/activate
            pip install -r requirements.txt
            
            # ПРИНУДИТЕЛЬНО освобождаем порт 5001
            echo "🔫 Killing processes on port 5001..."
            sudo kill -9 $(sudo lsof -t -i:5001) 2>/dev/null || true
            sleep 2
            
            # Перезапускаем сервис
            echo "🔄 Restarting flaskapp service..."
            sudo systemctl daemon-reload
            sudo systemctl restart flaskapp
            
            # Даем больше времени на запуск
            sleep 10
            
            # Проверяем статус
            if sudo systemctl is-active --quiet flaskapp; then
              echo "✅ Service restarted successfully"
            else
              echo "❌ Service failed to start"
              sudo systemctl status flaskapp
              exit 1
            fi
