name: CI/CD Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Можно добавить pytest, если есть тесты
          # pytest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            echo "🚀 Starting deployment..."
            
            cd /home/pyScriptUploadExcelFile
            
            git pull origin master
            
            if [ ! -d "venv" ]; then
              echo "🐍 Creating virtual environment..."
              python3 -m venv venv
            fi
            
            source venv/bin/activate
            
            pip install -r requirements.txt
            
            sudo fuser -k 5001/tcp 2>/dev/null || true
            sleep 2
            
            sudo systemctl daemon-reload
            sudo systemctl restart flaskapp
            
            sleep 5
            
            if sudo systemctl is-active --quiet flaskapp; then
              echo "✅ Deployment successful!"
            else
              echo "❌ Service failed to start"
              sudo systemctl status flaskapp
              exit 1
            fi
